In [2]:
import pandas as pd
import numpy as np

In [3]:
np.ones(3)  #returns a 1D array of 3 ones

array([1., 1., 1.])

In [4]:
np.ones((5,2), dtype=int) # returns 5x2 matrix with all ones (as integers)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [5]:
a= np.ones((2,1))
a

array([[1.],
       [1.]])

In [6]:
s=(2,2)
s= np.ones(s)
s

array([[1., 1.],
       [1., 1.]])

In [7]:
np.zeros(3) #returns a 1D array of 3 zeros

array([0., 0., 0.])

In [8]:
np.zeros((5,2), dtype=int) # returns 5x2 matrix with all zeros (as integers)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [9]:
a= np.zeros((2,1))
a

array([[0.],
       [0.]])

In [10]:
a=np.random.rand(2,3)  #returns a 2x3 matrix constaining random numbers from 0 to 1
a

array([[0.8767515 , 0.28438877, 0.19039719],
       [0.59962305, 0.62888088, 0.0079363 ]])

In [11]:
np.random.seed(0)


In [12]:
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [13]:
np.random.seed(0)
np.random.rand(2,3)    #returns the same set of random numbers

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

### Dealing with numpy array

In [14]:
# Creating a numpy array
x=[1,2,3]
np.array(x)

array([1, 2, 3])

In [15]:
# Accessing elements of a numpy array
x=[[1,2,3],[4,5,6]]
a=np.array(x)
a[0][0]

1

In [16]:
a[0][0]=10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [17]:
# Element-wise multiplication of two array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.multiply(a,b)       #Multiplication index wise

array([[ 5, 12],
       [21, 32]])

In [18]:
#Matrix Multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [19]:
#Dot product of 2 vectors (3*1 + 2*4)
a=np.array([1,2])
b=np.array([3,4])
np.dot(a,b)

11

In [20]:
#Cross product of 2 vectors (works with lists as well)
x = np.array([1, 2])
y = np.array([4, 5, 6])
np.cross(x, y)

array([12, -6, -3])

In [21]:
#Inverse of a list
x=np.array([[1,2],[3,4]])
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
#Transpose of a matrix
x=np.array([[1,2],[3,4]])
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [23]:
#Determinant of a matrix
x=np.array([[1,2],[3,4]])
np.linalg.det(x)

-2.0000000000000004

In [24]:
#Shape of the numpy array
x=np.array([[1,2],[3,4]])
x.shape

(2, 2)

In [28]:
#Creating an identity matrix of order n (Identity numpy array of order n)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])